## travis config with updated tools
## see: http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/


# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9


before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev
  - sudo apt-get install -y libgtest-dev
  - sudo apt-get install -y cppcheck
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

script:
  - make COMPILER=$COMPILER
  - make COMPILER=$COMPILER test

